# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewKoalaCli < Formula
  desc "CLI for Koala Ops."
  homepage "https://www.koalaops.com"
  version "0.0.202"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/KoalaOps/koala-backend/releases/download/0.0.202/koala-backend_Darwin_arm64"
      sha256 "b1bae79d941e51cd796a621dd2632085486b015a8a99031b057d695e41fb4085"

      def install
        bin.install "koala-backend_Darwin_arm64" => "koala"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KoalaOps/koala-backend/releases/download/0.0.202/koala-backend_Linux_x86_64"
      sha256 "6e9ffaa8a9227bc7c00ac17c6878f3745c7edbbfe53ff1cc6f0d66b6b9cfd5de"

      def install
        bin.install "koala-backend_Linux_x86_64" => "koala"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KoalaOps/koala-backend/releases/download/0.0.202/koala-backend_Linux_arm64"
      sha256 "c73616c7528b5145ed29d1a8b9e24d43a790dab7d5939a7ee024372cced44b2a"

      def install
        bin.install "koala-backend_Linux_arm64" => "koala"
      end
    end
  end
end
