# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewKoalaCli < Formula
  desc "CLI for Koala Ops."
  homepage "https://www.koalaops.com"
  version "0.0.203"

  on_macos do
    url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.203/koala_cli_Darwin_all"
    sha256 "3741d7555bb94069c757a3cdc3a76c1832a30a8bd6e0ec5b559f17629b51563c"

    def install
      bin.install "koala_cli_Darwin_all" => "koala"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.203/koala_cli_Linux_x86_64"
      sha256 "e865f82cf119d93fb5deb7e8f5fc7696df8f81a035b8e504bfe9019826d45e29"

      def install
        bin.install "koala_cli_Linux_x86_64" => "koala"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.203/koala_cli_Linux_arm64"
      sha256 "41571d08d5431d9dd2a49776789d0022d23cefaf925893da15290af698738f02"

      def install
        bin.install "koala_cli_Linux_arm64" => "koala"
      end
    end
  end
end
