# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koala < Formula
  desc "CLI for Koala Ops."
  homepage "https://www.koalaops.com"
  version "0.0.207"

  on_macos do
    url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.207/koala_cli_Darwin_all"
    sha256 "5aa5bd056b9b7dde6d652ae124975e2fab3f6f32d6bcb13d2986d9e1982b0544"

    def install
      bin.install "koala_cli_Darwin_all" => "koala"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.207/koala_cli_Linux_arm64"
      sha256 "378346c0bb1d9be72a74d43fa533262746e96cf9b4833e4310e3f3e92b6ef2b3"

      def install
        bin.install "koala_cli_Linux_arm64" => "koala"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.207/koala_cli_Linux_x86_64"
      sha256 "d473afa9e781497a366046d1c6bd7d345533ff07c05f589694a8bb2a165d4cb1"

      def install
        bin.install "koala_cli_Linux_x86_64" => "koala"
      end
    end
  end
end
