# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koala < Formula
  desc "CLI for Koala Ops."
  homepage "https://www.koalaops.com"
  version "0.0.204"

  on_macos do
    url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.204/koala_cli_Darwin_all"
    sha256 "6c2a2eb4e755fd286dd47e059cf66422d87193bbc1f339bde32ed7452fb1ccc2"

    def install
      bin.install "koala_cli_Darwin_all" => "koala"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.204/koala_cli_Linux_arm64"
      sha256 "2ac12647d52b3f1f78701f8fa1e0af9c5a669b35dcf11d3ca973170e1d33b88c"

      def install
        bin.install "koala_cli_Linux_arm64" => "koala"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.204/koala_cli_Linux_x86_64"
      sha256 "e4d03ab9b8b3689ca8c78ff5f06d629ae0a614bde265cf53462473eaafedbd15"

      def install
        bin.install "koala_cli_Linux_x86_64" => "koala"
      end
    end
  end
end
