# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koala < Formula
  desc "CLI for Koala Ops."
  homepage "https://www.koalaops.com"
  version "0.0.223"

  on_macos do
    url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.223/koala_cli_Darwin_all"
    sha256 "e9e23b4b4fd87f350039b41116f3263ff4af3f8f2e14dd94c5ffeaa25b12d326"

    def install
      bin.install "koala_cli_Darwin_all" => "koala"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.223/koala_cli_Linux_x86_64"
      sha256 "90a315028b9cb2a18f7cf577a21c28e54ae247db3bce431953e7dd7dd264c74d"

      def install
        bin.install "koala_cli_Linux_x86_64" => "koala"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KoalaOps/koala-cli/releases/download/0.0.223/koala_cli_Linux_arm64"
      sha256 "3c3ffc9e87a65a11c8c2b420ddc6fb522798fd90ae60949f8d9280f016ea8eec"

      def install
        bin.install "koala_cli_Linux_arm64" => "koala"
      end
    end
  end
end
